language: node_js
node_js:
  - 8.10.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  ssh_known_hosts: lir.com
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_c6330836dc8b_key -iv $encrypted_c6330836dc8b_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
install:
  - npm install
script:
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
