language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_c6330836dc8b_key -iv $encrypted_c6330836dc8b_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
install:
  - npm install
  - npm test
deploy:
  script: .travis/deploy.sh

